// Import Redux Toolkit's createSlice for defining the slice
import { createSlice } from '@reduxjs/toolkit';

/**
 * Get the initial theme from localStorage or default to 'light'
 * @returns {string} The theme mode ('light' or 'dark')
 */
const getInitialTheme = () => {
  // Retrieve saved theme from localStorage
  const savedTheme = localStorage.getItem('theme');
  // Return saved theme or default to 'light'
  return savedTheme || 'light';
};

/**
 * Redux slice for managing application theme (light/dark mode)
 * Persists theme preference to localStorage and applies CSS classes
 */
const themeSlice = createSlice({
  // Name of the slice for action type generation
  name: 'theme',
  // Initial state with theme mode from localStorage
  initialState: {
    mode: getInitialTheme(), // Current theme mode
  },
  reducers: {
    /**
     * Toggle between light and dark theme
     * Updates state, localStorage, and DOM classes
     * @param {object} state - Current state
     */
    toggleTheme: (state) => {
      // Switch mode between 'light' and 'dark'
      state.mode = state.mode === 'light' ? 'dark' : 'light';
      // Persist to localStorage
      localStorage.setItem('theme', state.mode);

      // Apply or remove 'dark' class on document root for CSS theming
      if (state.mode === 'dark') {
        document.documentElement.classList.add('dark');
      } else {
        document.documentElement.classList.remove('dark');
      }
    },
    /**
     * Set theme to a specific mode
     * Updates state, localStorage, and DOM classes
     * @param {object} state - Current state
     * @param {object} action - Action payload with theme mode
     */
    setTheme: (state, action) => {
      // Set mode to provided value
      state.mode = action.payload;
      // Persist to localStorage
      localStorage.setItem('theme', state.mode);

      // Apply or remove 'dark' class on document root for CSS theming
      if (state.mode === 'dark') {
        document.documentElement.classList.add('dark');
      } else {
        document.documentElement.classList.remove('dark');
      }
    },
  },
});

// Export action creators generated by createSlice
export const { toggleTheme, setTheme } = themeSlice.actions;
// Export the reducer function
export default themeSlice.reducer;